//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiscManageMaster.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DiscManageMaster.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static byte[] About {
            get {
                object obj = ResourceManager.GetObject("About", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] Disc {
            get {
                object obj = ResourceManager.GetObject("Disc", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] Help {
            get {
                object obj = ResourceManager.GetObject("Help", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] LocalFolder {
            get {
                object obj = ResourceManager.GetObject("LocalFolder", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] MyCollections {
            get {
                object obj = ResourceManager.GetObject("MyCollections", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] Options {
            get {
                object obj = ResourceManager.GetObject("Options", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] Removable {
            get {
                object obj = ResourceManager.GetObject("Removable", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] SearchResult {
            get {
                object obj = ResourceManager.GetObject("SearchResult", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0431FE682050D0EA67378D747DF74582.
        /// </summary>
        public static string String4 {
            get {
                return ResourceManager.GetString("String4", resourceCulture);
            }
        }
        
        public static byte[] Welcome {
            get {
                object obj = ResourceManager.GetObject("Welcome", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
